From mikael@example.com  Wed Aug 10 10:01:06 2005
Return-Path: <mikael@example.com>
X-Original-To: jobblistan@example.com
Delivered-To: jobblistan@example.com
Received: from localhost (localhost.localdomain [127.0.0.1])
	by mail.example.com (Postfix) with ESMTP id 9AC7B1D34B9
	for <jobblistan@example.com>; Wed, 10 Aug 2005 10:01:06 +0200 (CEST)
Received: from mail.example.com ([127.0.0.1])
 by localhost (morbo [127.0.0.1]) (amavisd-new, port 10024) with LMTP
 id 28202-01-37 for <jobblistan@example.com>;
 Wed, 10 Aug 2005 10:01:06 +0200 (CEST)
Received: from shell.example.com (shell.example.com [129.16.214.9])
	by mail.example.com (Postfix) with ESMTP id 706781D323A
	for <jobblistan@example.com>; Wed, 10 Aug 2005 10:01:06 +0200 (CEST)
Received: by shell.example.com (Postfix, from userid 27846)
	id C405E6B7A; Wed, 10 Aug 2005 10:01:07 +0200 (CEST)
Received: from localhost (localhost [127.0.0.1])
	by shell.example.com (Postfix) with ESMTP id BAF406B73
	for <jobblistan@example.com>; Wed, 10 Aug 2005 10:01:07 +0200 (CEST)
Date: Wed, 10 Aug 2005 10:01:07 +0200 (CEST)
From: Mikael Johansson <mikael@example.com>
X-X-Sender: mikl@shell.example.com
To: jobblistan@example.com
Subject: =?iso-8859-1?Q?Manual_=C4rendehantering?= (fwd)
Message-ID: <Pine.LNX.4.60.0508101001000.10447@shell.example.com>
MIME-Version: 1.0
Content-Type: MULTIPART/Mixed; BOUNDARY="=====================_14133663==_"
Content-ID: <Pine.LNX.4.60.0508101001001.10447@shell.example.com>
X-Virus-Scanned: by amavisd-new at example.com

  This message is in MIME format.  The first part should be readable text,
  while the remaining parts are likely unreadable without MIME-aware tools.

--=====================_14133663==_
Content-Type: TEXT/PLAIN; CHARSET=iso-8859-1; FORMAT=flowed
Content-Transfer-Encoding: 8BIT
Content-ID: <Pine.LNX.4.60.0508101001002.10447@shell.example.com>



-- 
Mikael Johansson

---------- Forwarded message ----------
Date: Tue, 02 Aug 2005 12:48:00 +0200
From: Katarina <katarina@example.com>
To: mikael@example.com
Subject: Manual Ärendehantering

Hej 
--=====================_14133663==_
Content-Type: APPLICATION/MSWORD; NAME*="ISO-8859-1''%C4rendehantering.doc"; X-MAC-TYPE=42494E41; X-MAC-CREATOR=4D535744
Content-Transfer-Encoding: BASE64
Content-ID: <Pine.LNX.4.60.0508101001003.10447@shell.example.com>
Content-Description: 
Content-Disposition: ATTACHMENT; FILENAME*="ISO-8859-1''%C4rendehantering.doc"

Zm9v==
--=====================_14133663==_
Content-Type: TEXT/PLAIN; CHARSET=iso-8859-1; FORMAT=flowed
Content-Transfer-Encoding: QUOTED-PRINTABLE
Content-ID: <Pine.LNX.4.60.0508101001004.10447@shell.example.com>
Content-Description: 


----------------------------------------------------------
Webb: www.example.com
----------------------------------------------------------

--=====================_14133663==_--
