From mikael@example.com  Tue Nov  2 15:16:26 2004
Return-Path: <mikael@example.com>
X-Original-To: issues+_unit_test@example.com
Delivered-To: issues+_unit_test@example.com
Received: from localhost (localhost.localdomain [127.0.0.1])
        by mail.example.com (Postfix) with ESMTP id 771F31D316C
        for <issues+_unit_test@example.com>; Tue,  2 Nov 2004 15:16:26  0100 (CET)
Received: from mail.example.com ([127.0.0.1])
 by localhost (morbo [127.0.0.1]) (amavisd-new, port 10024) with LMTP
 id 31212-01-82 for <issues+_unit_test@example.com>;
 Tue,  2 Nov 2004 15:16:26  0100 (CET)
Received: from shell.example.com (shell.example.com [129.16.214.9])
        by mail.example.com (Postfix) with ESMTP id 4C5701D3164
        for <issues+_unit_test@example.com>; Tue,  2 Nov 2004 15:16:26  0100 (CET)
Received: by shell.example.com (Postfix, from userid 27846)
        id 413B156803; Tue,  2 Nov 2004 15:15:33  0100 (CET)
Received: from localhost (localhost [127.0.0.1])
        by shell.example.com (Postfix) with ESMTP id 3D8A357001
        for <issues+_unit_test@example.com>; Tue,  2 Nov 2004 15:15:33  0100 (CET)
Date: Tue, 2 Nov 2004 15:15:33  0100 (CET)
From: Mikael Johansson <mikael@example.com>
X-X-Sender: mikl@shell.example.com
To: issues+_unit_test@example.com
Cc: issues+_unit_test2@example.com
Bcc: issues+_unit_test3@example.com
Subject: Subject: Protokoll =?ISO-8859-1?Q?arbetsm=F6te_1_=2Ctr=E5dl=F6sa_n=E4?=
Message-ID: <Pine.LNX.4.60.0411021515220.1874@shell.example.com>
MIME-Version: 1.0
Content-Type: TEXT/PLAIN; charset=US-ASCII; format=flowed
X-Virus-Scanned: by amavisd-new at example.com

Test message

-- 
Mikael Johansson
Email: mikael@example.com Phone: ( 46) 123-123 12345