From example@example.com  Thu Feb 17 11:52:41 2005
Return-Path: <example@example.com>
X-Original-To: example@example.com
Delivered-To: example@example.com
Received: from localhost (localhost.localdomain [127.0.0.1])
	by mail.example.com (Postfix) with ESMTP id 3A4E01D395B
	for <example@example.com>; Thu, 17 Feb 2005 11:52:41 +0100 (CET)
Received: from mail.example.com ([127.0.0.1])
 by localhost (example [127.0.0.1]) (amavisd-new, port 10024) with LMTP
 id 16378-01-28 for <example@example.com>;
 Thu, 17 Feb 2005 11:52:40 +0100 (CET)
Received: from example.com (example.com [129.16.214.122])
	by mail.example.com (Postfix) with ESMTP id 5D9A11D394E
	for <example@example.com>; Thu, 17 Feb 2005 11:52:40 +0100 (CET)
Message-ID: <4214777A.2010304@example.com>
Date: Thu, 17 Feb 2005 11:52:42 +0100
From: Example <example@example.com>
User-Agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.5) Gecko/20031013 Thunderbird/0.3
X-Accept-Language: en-us, en
MIME-Version: 1.0
To: example@example.com
Subject: Protokoll =?ISO-8859-1?Q?arbetsm=F6te_1_=2Ctr=E5dl=F6sa_n=E4?=
 =?ISO-8859-1?Q?t__ID=3A21198?=
Content-Type: multipart/mixed;
 boundary="------------060009010703010203030609"
X-Virus-Scanned: by amavisd-new at example.com

This is a multi-part message in MIME format.
--------------060009010703010203030609
Content-Type: text/plain; charset=ISO-8859-1; format=flowed
Content-Transfer-Encoding: 8bit

test
--------------060009010703010203030609
Content-Type: message/rfc822;
 name="Protokoll =?ISO-8859-1?Q?arbetsm=F6te_1_=2Ctr=E5dl=F6sa_n=E4t=2Eeml?="
Content-Transfer-Encoding: 7bit
Content-Disposition: inline;
 filename="Protokoll =?ISO-8859-1?Q?arbetsm=F6te_1_=2Ctr=E5dl=F6sa_n=E4t=2Eeml?="

Return-Path: <example@example.com>
X-Original-To: example@example.com
Delivered-To: example@example.com
Received: from localhost (localhost.localdomain [127.0.0.1])
	by mail.example.com (Postfix) with ESMTP id 0B59B1D38D3
	for <example@example.com>; Fri, 11 Feb 2005 13:33:06 +0100 (CET)
Received: from mail.example.com ([127.0.0.1])
 by localhost (example [127.0.0.1]) (amavisd-new, port 10024) with LMTP
 id 19757-01-72 for <example@example.com>;
 Fri, 11 Feb 2005 13:33:05 +0100 (CET)
Received: from example.com (unknown [194.17.253.230])
	by mail.example.com (Postfix) with ESMTP id 080731D38D2
	for <example@example.com>; Fri, 11 Feb 2005 13:32:59 +0100 (CET)
Received: from example.com (example [127.0.0.1])
	by example.com (8.12.10/8.12.10) with ESMTP id j1BCWLiR018617
	for <example@example.com>; Fri, 11 Feb 2005 13:32:26 +0100 (CET)
Received: from example (example.com [127.0.0.1])
	(authenticated bits=0)
	by example.com (8.12.10/8.12.10) with ESMTP id j1BCWCkf018600;
	Fri, 11 Feb 2005 13:32:12 +0100 (CET)
Message-Id: <200502111232.j1BCWCkf018600@example.com>
From: "Example" <example@example.com>
To: "Example" <example@example.com>
Cc: "Example" <example@example.com>
Subject: =?iso-8859-1?Q?Protokoll_arbetsm=F6te_1_=2Ctr=E5dl=F6sa_n=E4t?=
Date: Fri, 11 Feb 2005 13:32:36 +0100
MIME-Version: 1.0
Content-Type: multipart/mixed;
	boundary="----=_NextPart_000_002A_01C5103E.27EB5C80"
X-Mailer: Microsoft Office Outlook, Build 11.0.6353
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2900.2180
Thread-Index: AcUQNcQxtl3ZPoMzRNSmfpqIR0CSgw==
X-Virus-Scanned: by amavisd-new at example.com

This is a multi-part message in MIME format.

------=_NextPart_000_002A_01C5103E.27EB5C80
Content-Type: multipart/alternative;
	boundary="----=_NextPart_001_002B_01C5103E.27EB5C80"


------=_NextPart_001_002B_01C5103E.27EB5C80
Content-Type: text/plain;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

Text body

------=_NextPart_001_002B_01C5103E.27EB5C80
Content-Type: text/html;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<html xmlns:v=3D"urn:schemas-microsoft-com:vml" =
xmlns:o=3D"urn:schemas-microsoft-com:office:office" =
xmlns:w=3D"urn:schemas-microsoft-com:office:word" =
xmlns:st1=3D"urn:schemas-microsoft-com:office:smarttags" =
xmlns=3D"http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=3DContent-Type content=3D"text/html; =
charset=3Diso-8859-1">
<meta name=3DGenerator content=3D"Microsoft Word 11 (filtered medium)">
<o:SmartTagType =
namespaceuri=3D"urn:schemas-microsoft-com:office:smarttags"
 name=3D"PersonName" downloadurl=3D"http://www.microsoft.com"/>
<!--[if !mso]>
<style>
st1\:*{behavior:url(#default#ieooui) }
</style>
<![endif]-->
<style>
<!--
 /* Style Definitions */
 p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	margin-bottom:.0001pt;
	font-size:12.0pt;
	font-family:"Times New Roman";}
a:link, span.MsoHyperlink
	{color:blue;
	text-decoration:underline;}
a:visited, span.MsoHyperlinkFollowed
	{color:purple;
	text-decoration:underline;}
p.MsoAutoSig, li.MsoAutoSig, div.MsoAutoSig
	{margin:0cm;
	margin-bottom:.0001pt;
	font-size:12.0pt;
	font-family:"Times New Roman";}
span.E-postmall17
	{mso-style-type:personal-compose;
	font-family:Arial;
	color:windowtext;}
@page Section1
	{size:595.3pt 841.9pt;
	margin:70.85pt 70.85pt 70.85pt 70.85pt;}
div.Section1
	{page:Section1;}
-->
</style>
<!--[if gte mso 9]><xml>
 <o:shapedefaults v:ext=3D"edit" spidmax=3D"1026" />
</xml><![endif]--><!--[if gte mso 9]><xml>
 <o:shapelayout v:ext=3D"edit">
  <o:idmap v:ext=3D"edit" data=3D"1" />
 </o:shapelayout></xml><![endif]-->
</head>

<body lang=3DSV link=3Dblue vlink=3Dpurple>

<div class=3DSection1>

<p class=3DMsoNormal><font size=3D2 face=3DArial><span =
style=3D'font-size:10.0pt;
font-family:Arial'>Text body<o:p></o:p></span></font></p>

</body>

</html>

------=_NextPart_001_002B_01C5103E.27EB5C80--

------=_NextPart_000_002A_01C5103E.27EB5C80
Content-Type: application/msword;
	name="=?iso-8859-1?Q?M1=5Ftr=E5dl=F6sa_n=E4t_GU=5F050208.doc?="
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
	filename="=?iso-8859-1?Q?M1=5Ftr=E5dl=F6sa_n=E4t_GU=5F050208.doc?="

Zm9v

------=_NextPart_000_002A_01C5103E.27EB5C80
Content-Type: application/msword;
	name="=?iso-8859-1?Q?Tr=E5dl=F6san=E4t=5FProjektspecifikation=5FPA6.doc?="
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
	filename="=?iso-8859-1?Q?Tr=E5dl=F6san=E4t=5FProjektspecifikation=5FPA6.doc?="

Zm9v

------=_NextPart_000_002A_01C5103E.27EB5C80--



--------------060009010703010203030609--

