From mikael@example.com  Tue Jan 11 14:18:11 2005
Return-Path: <mikael@example.com>
X-Original-To: example@example.com
Delivered-To: example@example.com
Received: from localhost (localhost [127.0.0.1])
	by example.com (Postfix) with ESMTP id 87E567F001
	for <jobblistan-devel@example.com>; Tue, 11 Jan 2005 14:18:02 +0100 (CET)
Date: Tue, 11 Jan 2005 14:18:02 +0100 (CET)
From: Mikael Johansson <mikael@example.com>
X-X-Sender: mikl@example.com
To: example@example.com
Subject: SOAP-API (fwd) ID:1985
Message-ID: <Pine.LNX.4.60.0501111415240.15380@example.com>
MIME-Version: 1.0
Content-Type: MULTIPART/Mixed; BOUNDARY="----=_NextPart_000_0010_01C4F7E2.86057270"

  This message is in MIME format.  The first part should be readable text,
  while the remaining parts are likely unreadable without MIME-aware tools.

------=_NextPart_000_0010_01C4F7E2.86057270
Content-Type: TEXT/PLAIN; charset=ISO-8859-1; format=flowed
Content-Transfer-Encoding: 8BIT

test


------=_NextPart_000_0010_01C4F7E2.86057270
Content-Type: APPLICATION/PDF; NAME="attachment.txt"
Content-Transfer-Encoding: BASE64
Content-ID: <Pine.LNX.4.60.0501111415241.15380@example.com>
Content-Description: 
Content-Disposition: ATTACHMENT; FILENAME="attachment.txt"

Zm9v

------=_NextPart_000_0010_01C4F7E2.86057270--
