MIME-Version: 1.0
Content-Type: MULTIPART/Mixed; BOUNDARY=------------000000000906020700000807
Content-ID: <Pine.LNX.4.60.0510181405061.19759@example.com>

  This message is in MIME format.  The first part should be readable text,
  while the remaining parts are likely unreadable without MIME-aware tools.

--------------000000000906020700000807
Content-Type: TEXT/PLAIN; CHARSET=ISO-8859-1; FORMAT=flowed
Content-Transfer-Encoding: 8BIT


---------- Forwarded message ----------
Date: Tue, 18 Oct 2005 13:44:10 +0200

Test

--------------000000000906020700000807
Content-Type: APPLICATION/PDF; NAME*0="SD =?ISO-8859-1?Q?arbetsfl=F6de_mot_Thirdline_inkl_funktioner?==?ISO-8859-1?Q";
        NAME*1="?=2Epdf?="
Content-Transfer-Encoding: BASE64
Content-Description: 
Content-Disposition: INLINE; FILENAME*0="SD =?ISO-8859-1?Q?arbetsfl=F6de_mot_Thirdline_inkl_funktioner?==?ISO-8859-1?Q";
        FILENAME*1="?=2Epdf?="

Zm9v==
--------------000000000906020700000807
Content-Type: APPLICATION/PDF; NAME="=?ISO-8859-1?Q?=C4rendefl=F6de_inom_Servicedesk=2Epdf?="
Content-Transfer-Encoding: BASE64
Content-Description: 
Content-Disposition: INLINE; FILENAME="=?ISO-8859-1?Q?=C4rendefl=F6de_inom_Servicedesk=2Epdf?="

Zm9v==
--------------000000000906020700000807
Content-Type: APPLICATION/PDF; NAME="=?ISO-8859-1?Q?Fl=F6de_i_ord=2Epdf?="
Content-Transfer-Encoding: BASE64

Zm9v==
--------------000000000906020700000807
Content-Type: APPLICATION/PDF; NAME*0="=?ISO-8859-1?Q?=D6verblick_av_=E4rende_rutin_f=F6r_Servicedesk_?==?ISO-8859-1?Q?m";
        NAME*1="ot__Thirdline=2Epdf?="
Content-Transfer-Encoding: BASE64
Content-Description: 
Content-Disposition: INLINE; FILENAME*0="=?ISO-8859-1?Q?=D6verblick_av_=E4rende_rutin_f=F6r_Servicedesk_?==?ISO-8859-1?Q?m";
        FILENAME*1="ot__Thirdline=2Epdf?="

Zm9v==
--------------000000000906020700000807--
