From mikael@example.com  Tue Nov  2 15:16:26 2004
Return-Path: <mikael@example.com>
X-Original-To: issues@example.com
Delivered-To: issues@example.com
Received: from localhost (localhost.localdomain [127.0.0.1])
        by mail.example.com (Postfix) with ESMTP id 771F31D316C
        for <issues@example.com>; Tue,  2 Nov 2004 15:16:26  0100 (CET)
Received: from mail.example.com ([127.0.0.1])
 by localhost (morbo [127.0.0.1]) (amavisd-new, port 10024) with LMTP
 id 31212-01-82 for <issues@example.com>;
 Tue,  2 Nov 2004 15:16:26  0100 (CET)
Received: from shell.example.com (shell.example.com [129.16.214.9])
        by mail.example.com (Postfix) with ESMTP id 4C5701D3164
        for <issues@example.com>; Tue,  2 Nov 2004 15:16:26  0100 (CET)
Received: by shell.example.com (Postfix, from userid 27846)
        id 413B156803; Tue,  2 Nov 2004 15:15:33  0100 (CET)
Received: from localhost (localhost [127.0.0.1])
        by shell.example.com (Postfix) with ESMTP id 3D8A357001
        for <issues@example.com>; Tue,  2 Nov 2004 15:15:33  0100 (CET)
Date: Tue, 2 Nov 2004 15:15:33  0100 (CET)
From: Mikael Johansson <mikael@example.com>
X-X-Sender: mikl@shell.example.com
To: issues@example.com
Subject: Test
Message-ID: <Pine.LNX.4.60.0411021515220.1874@shell.example.com>
MIME-Version: 1.0
Content-Type: MULTIPART/MIXED; BOUNDARY="276892118-1590636316-1101117277=:26478"
X-Virus-Scanned: by amavisd-new at example.com

  This message is in MIME format.  The first part should be readable text,
  while the remaining parts are likely unreadable without MIME-aware tools.

--276892118-1590636316-1101117277=:26478
Content-Type: TEXT/PLAIN; charset=US-ASCII; format=flowed

test

--276892118-1590636316-1101117277=:26478
Content-Type: application/pdf; charset=US-ASCII; name="foo6.txt"
Content-Transfer-Encoding: base64
Content-ID: <Pine.LNX.4.60.0411221054360.26478@example.com>
Content-Description: 
Content-Disposition: attachment; filename="foo6.txt"

Zm9v

--276892118-1590636316-1101117277=:26478--