Content-Type: multipart/mixed; boundary="===============0966435334=="

  This message is in MIME format.  The first part should be readable text,
  while the remaining parts are likely unreadable without MIME-aware tools.

--===============0966435334==
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

Test

--===============0966435334==
Content-Type: application/octet-stream; name
Content-Disposition: attachment; filename
Content-Transfer-Encoding: base64

Zm9v=
--===============0966435334==--
