Return-Path: <mikael@example.com>
X-Original-To: mikl@example.com
Delivered-To: mikl@example.com
Received: from [129.16.214.109] (term109.example.com [129.16.214.109])
	by mail.example.com (Postfix) with ESMTP id B2C8F1D31C7
	for <mikl@example.com>; Fri, 25 Aug 2006 12:43:55 +0200 (CEST)
Message-ID: <44EED46D.3020903@example.com>
Date: Fri, 25 Aug 2006 12:43:57 +0200
From: Mikael Johansson <mikael@example.com>
User-Agent: Thunderbird 1.5.0.5 (Windows/20060719)
MIME-Version: 1.0
To: Mikael Johansson <mikl@example.com>
Subject: Test sign using PGP/MIME
X-Enigmail-Version: 0.94.0.0
Content-Type: multipart/signed; micalg=pgp-sha1;
 protocol="application/pgp-signature";
 boundary="------------enig3417240F8E01C45488ECB1C1"
X-Virus-Scanned: amavisd-new at example.com
X-Virus-Scanned: amavisd-new at example.com

This is an OpenPGP/MIME signed message (RFC 2440 and 3156)
--------------enig3417240F8E01C45488ECB1C1
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

Test sign using PGP/MIME =E5=E4=F6

--=20
Mikael Johansson
Chalmers University of Technology, Computer Service
Email: mikl AT chalmers DOT se Phone: (+46) 031-772 5912


--------------enig3417240F8E01C45488ECB1C1
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.3 (MingW32)

iD8DBQFE7tRtwpDE+LemqakRAm4mAJsGA+LhwXt0k5Fyrp5UYF6r6XdMnQCggHhi
wGtn4O0QS6Yav3YdIVoLm9o=
=xsov
-----END PGP SIGNATURE-----

--------------enig3417240F8E01C45488ECB1C1--
