From mikael@example.com  Tue Nov  2 15:16:26 2004
Return-Path: <mikael@example.com>
X-Original-To: issues _unit_test@example.com
Delivered-To: issues _unit_test@example.com
Date: Tue, 2 Nov 2004 15:15:33  0100 (CET)
From: Mikael Johansson <mikael+spam@example.com>
X-X-Sender: mikl@shell.example.com
To: example@example.com
cc: issues+_unit_test@example.com
Subject: Fwd: Test
Message-ID: <Pine.LNX.4.60.0411021515220.1874@shell.example.com>
MIME-Version: 1.0
Content-Type: TEXT/PLAIN; charset=US-ASCII; format=flowed
X-Virus-Scanned: by amavisd-new at example.com

Foobar

On Tue, 2 Nov 2004 foo@example.com wrote:
>
> Test message
>