Date: Tue, 2 Nov 2004 15:15:33  0100 (CET)
From: Mikael Johansson <mikael@example.com>
To: issues+__PROJECT__@example.com
Cc: issues+@example.com
Subject: __SUBJECT__
MIME-Version: 1.0
Content-Type: TEXT/PLAIN; charset=US-ASCII; format=flowed
X-Spam-Status: Yes, score=25.685 tagged_above=0 required=5
 tests=[BAYES_99=3.5, HTML_MESSAGE=0.001, URIBL_AB_SURBL=3.812, URIBL_BLACK=3,
 URIBL_JP_SURBL=4.087, URIBL_OB_SURBL=3.008, URIBL_SBL=1.639,
 URIBL_SC_SURBL=4.498, URIBL_WS_SURBL=2.14]
X-Spam-Flag: YES

This is a faked SPAM message

-- 
Mikael Johansson
Email: mikael@example.com Phone: ( 46) 123-123 12345