Return-Path: <mikael@example.com>
X-Original-To: mikl@example.com
Delivered-To: mikl@example.com
Received: from localhost (localhost.localdomain [127.0.0.1])
	by mail.example.com (Postfix) with ESMTP id F3C671D383E
	for <mikl@example.com>; Tue, 29 Aug 2006 14:47:08 +0200 (CEST)
Received: from mail.example.com ([127.0.0.1])
 by localhost (mail.example.com [127.0.0.1]) (amavisd-new, port 10024)
 with LMTP id 24736-01-30 for <mikl@example.com>;
 Tue, 29 Aug 2006 14:47:08 +0200 (CEST)
Received: from [129.16.214.109] (term109.example.com [129.16.214.109])
	by mail.example.com (Postfix) with ESMTP id 3DCDD1D3186
	for <mikl@example.com>; Tue, 29 Aug 2006 14:47:08 +0200 (CEST)
Message-ID: <44F4374E.3060405@example.com>
Date: Tue, 29 Aug 2006 14:47:10 +0200
From: Mikael Johansson <mikael@example.com>
User-Agent: Thunderbird 1.5.0.5 (Windows/20060719)
MIME-Version: 1.0
To: Johansson Mikael <mikl@example.com>
Subject: Test sign using PGP/MIME
X-Enigmail-Version: 0.94.1.0
Content-Type: multipart/signed; micalg=pgp-sha1;
 protocol="application/pgp-signature";
 boundary="------------enigA35659EA99D4FCED0D448CDA"
X-Virus-Scanned: amavisd-new at example.com

This is an OpenPGP/MIME signed message (RFC 2440 and 3156)
--------------enigA35659EA99D4FCED0D448CDA
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

Test sign using


--------------enigA35659EA99D4FCED0D448CDA
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.3 (MingW32)

iD8DBQFE9DdOhwhXUN1gw3URAmDqAKC9agjAE0QG1aKwXWGCf2GzpCQV+QCgxblQ
2zwfNUNDyj+XHWuQ+ezgc54=
=xzHn
-----END PGP SIGNATURE-----

--------------enigA35659EA99D4FCED0D448CDA--
