Return-Path: <mikael@example.com>
X-Original-To: mikl@example.com
Delivered-To: mikl@example.com
Received: from localhost (localhost.localdomain [127.0.0.1])
	by mail.example.com (Postfix) with ESMTP id 640541D31E6
	for <mikl@example.com>; Tue, 29 Aug 2006 15:07:27 +0200 (CEST)
Received: from mail.example.com ([127.0.0.1])
 by localhost (mail.example.com [127.0.0.1]) (amavisd-new, port 10024)
 with LMTP id 26047-01-78 for <mikl@example.com>;
 Tue, 29 Aug 2006 15:07:26 +0200 (CEST)
Received: from [129.16.214.109] (term109.example.com [129.16.214.109])
	by mail.example.com (Postfix) with ESMTP id AEA941D31A4
	for <mikl@example.com>; Tue, 29 Aug 2006 15:07:26 +0200 (CEST)
Message-ID: <44F43C11.7000105@example.com>
Date: Tue, 29 Aug 2006 15:07:29 +0200
From: Mikael Johansson <mikael@example.com>
User-Agent: Thunderbird 1.5.0.5 (Windows/20060719)
MIME-Version: 1.0
To: Johansson Mikael <mikl@example.com>
Subject: Test sign using clearsign
X-Enigmail-Version: 0.94.1.0
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: 7bit
X-Virus-Scanned: amavisd-new at example.com

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Test sign using clearsign
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.3 (MingW32)

iD8DBQFE9DwRhwhXUN1gw3URAiQuAJ4qcK+6YGUraODBH5874Dq3+gQwvACgh+hR
whRd2/hwqlL8Em1JeFJEPa0=
=hk5I
-----END PGP SIGNATURE-----
